{% set python = "python >=3.9" %}

package:
  name: uwtools
  version: 0.1.0
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: 0
requirements:
  host:
    - pip
    - {{ python }}
  run:
    - boto3 1.22.*
    - f90nml 1.4.*
    - jinja2 3.0.*
    - jsonschema 4.17.*
    - pyyaml 6.0.*
    - {{ python }}
test:
  requires:
    - black 23.3.*
    - coverage 7.2.*
    - isort 5.12.*
    - mypy 1.4.*
    - pylint 2.17.*
    - pytest 7.4.*
about:
  license: LGPL
