# Read the Docs configuration (see https://docs.readthedocs.io/en/stable/config-file/v2.html)

version: 2
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    pre_build:
      - make meta
      - export UWTOOLS_VERSION=$(jq -r .version recipe/meta.json)
conda:
  environment: docs/environment.yml
# python:
#    install:
#      - requirements: docs/requirements.txt
sphinx:
  builder: html
  configuration: docs/conf.py
