[tool.black]
line-length = 100

[tool.coverage.report]
exclude_lines = ["@abstractmethod"]
fail_under = 94
show_missing = true
skip_covered = true

[tool.isort]
line_length = 100

[tool.mypy]
check_untyped_defs = true
follow_imports = "skip"
ignore_missing_imports = true

[tool.pylint.messages_control]
disable = [
  "C0103", "C0209", "C0302", "C0114",
  "R0903", "R0912", "R0913", "R0914", "R0915", "R1735",
]

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning:botocore.*"]
