name: Documentation
on:
  push:
    branches:
      - develop
      - feature/*
      - main/*
      - bugfix/*
    paths:
      - docs/**
  pull_request:
    types: [opened, reopened, synchronize]
env:
  PYTHONPATH: ${GITHUB_WORKSPACE}/src
jobs:
  create_documentation:
    runs-on: ubuntu-latest
    name: Deploy Documentation
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install/Upgrade Dependencies
      run: python -m pip install --upgrade pip sphinx sphinx-gallery sphinx_rtd_theme
    - name: Build Documentation
      run: .github/scripts/build-documentation
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Upload Documentation Artifacts
        path: artifact/documentation
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Upload Warnings Log
        path: artifact/doc_warnings.log
        if-no-files-found: ignore
